In [1]:
import warnings
from statsbombpy.api_client import NoAuthWarning

warnings.simplefilter("ignore", NoAuthWarning)

from socceraction.data.statsbomb import StatsBombLoader

In [2]:
api = StatsBombLoader(getter="remote", creds=None)

In [3]:
api.competitions()[:10]

,season_id,competition_id,competition_name,country_name,competition_gender,season_name
0,281,9,1. Bundesliga,Germany,male,2023/2024
1,27,9,1. Bundesliga,Germany,male,2015/2016
2,107,1267,African Cup of Nations,Africa,male,2023
3,4,16,Champions League,Europe,male,2018/2019
4,1,16,Champions League,Europe,male,2017/2018
5,2,16,Champions League,Europe,male,2016/2017
6,27,16,Champions League,Europe,male,2015/2016
7,26,16,Champions League,Europe,male,2014/2015
8,25,16,Champions League,Europe,male,2013/2014
9,24,16,Champions League,Europe,male,2012/2013

In [4]:
api.competitions()["competition_name"].unique()

array(['1. Bundesliga', 'African Cup of Nations', 'Champions League',
       'Copa America', 'Copa del Rey', "FA Women's Super League",
       'FIFA U20 World Cup', 'FIFA World Cup', 'Frauen Bundesliga',
       'Indian Super league', 'La Liga', 'Liga F', 'Liga Profesional',
       'Ligue 1', 'Major League Soccer', 'North American League', 'NWSL',
       'Premier League', 'Serie A', 'Serie A Women', 'UEFA Euro',
       'UEFA Europa League', "UEFA Women's Euro", "Women's World Cup"],
      dtype=object)

In [5]:
top_leagues = [
    "1. Bundesliga",
    "African Cup of Nations",
    "Champions League",
    "Copa America",
    "Copa del Rey",
    "FIFA World Cup",
    "La Liga",
    "Ligue 1",
    "Premier League",
    "Serie A",
    "UEFA Euro",
    "UEFA Europa League",
]

In [6]:
api.games(competition_id=16, season_id=4)

,game_id,season_id,competition_id,competition_stage,game_day,game_date,home_team_id,away_team_id,home_score,away_score,venue,referee
0,22912,4,16,Final,13,2019-06-01 21:00:00,38,24,0,2,Estádio Cívitas Metropolitano,Damir Skomina

In [7]:
events = api.events(game_id=3788741, load_360=True) 
events.head()

/Users/aranyeosakwe/oracle/.venv/lib/python3.12/site-packages/socceraction/data/statsbomb/loader.py:337: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  eventsdf["under_pressure"] = eventsdf["under_pressure"].fillna(False).astype(bool)
/Users/aranyeosakwe/oracle/.venv/lib/python3.12/site-packages/socceraction/data/statsbomb/loader.py:338: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  eventsdf["counterpress"] = eventsdf["counterpress"].fillna(False).astype(bool)

,game_id,event_id,period_id,team_id,player_id,type_id,type_name,index,timestamp,minute,...,extra,related_events,player_name,position_id,position_name,location,under_pressure,counterpress,visible_area_360,freeze_frame_360
0,3788741,59645e89-9c7f-46f2-b662-332c5b8bba12,1,909,NaN,35,Starting XI,1,0 days 00:00:00,0,...,"{'tactics': {'formation': 4141, 'lineup': [{'p...",[],NaN,NaN,NaN,NaN,False,False,NaN,NaN
1,3788741,f063a4b6-f5ad-4576-b31d-a8dbe50f693e,1,914,NaN,35,Starting XI,2,0 days 00:00:00,0,...,"{'tactics': {'formation': 433, 'lineup': [{'pl...",[],NaN,NaN,NaN,NaN,False,False,NaN,NaN
2,3788741,4d9693c5-29bb-4e73-8913-7ee7a4e465fc,1,909,NaN,18,Half Start,3,0 days 00:00:00,0,...,{},[5c53ec59-b0d0-4515-8fee-d973e0037b56],NaN,NaN,NaN,NaN,False,False,NaN,NaN
3,3788741,5c53ec59-b0d0-4515-8fee-d973e0037b56,1,914,NaN,18,Half Start,4,0 days 00:00:00,0,...,{},[4d9693c5-29bb-4e73-8913-7ee7a4e465fc],NaN,NaN,NaN,NaN,False,False,NaN,NaN
4,3788741,5c888f58-fe77-459b-ab3b-a2fa5fb8ab16,1,909,11086.0,30,Pass,5,0 days 00:00:00.878000,0,...,"{'pass': {'recipient': {'id': 8963, 'name': 'C...",[776e11e0-9e85-4226-9f9e-edefa3685288],Burak Yılmaz,23.0,Center Forward,"[60.0, 40.0]",False,False,"[0.0, 27.7649873094419, 19.2332231959735, 17.3...","[{'teammate': False, 'actor': False, 'keeper':..."

In [8]:
import socceraction.spadl as spadl

df_actions = spadl.statsbomb.convert_to_actions(events, home_team_id=909)
df_actions.head()

/Users/aranyeosakwe/oracle/.venv/lib/python3.12/site-packages/socceraction/spadl/statsbomb.py:53: UserWarning: Inferred xy_fidelity_version=2. If this is incorrect, please specify the correct version using the xy_fidelity_version argument
  warnings.warn(
/Users/aranyeosakwe/oracle/.venv/lib/python3.12/site-packages/socceraction/spadl/statsbomb.py:75: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  events["extra"].fillna({}, inplace=True)

,game_id,original_event_id,period_id,time_seconds,team_id,player_id,start_x,start_y,end_x,end_y,type_id,result_id,bodypart_id,action_id
0,3788741,5c888f58-fe77-459b-ab3b-a2fa5fb8ab16,1,0.878,909,11086.0,52.45625,34.0425,28.39375,43.5625,0,1,5,0
1,3788741,bea4235d-7e40-461c-bb82-6d473f5bb324,1,2.789,909,8963.0,28.39375,43.5625,31.63125,42.2025,21,1,0,1
2,3788741,84b9b798-0fbe-45bc-a4bf-3621959f29ce,1,4.288,909,8963.0,31.63125,42.2025,61.81875,3.6125,0,1,4,2
3,3788741,1615d483-101d-45c1-b554-04cf69897232,1,6.764,909,8541.0,61.81875,3.6125,61.55625,3.8675,21,1,0,3
4,3788741,39abab21-b9fc-4830-a7c4-f3cf6172df2c,1,6.866,909,8541.0,61.55625,3.8675,61.55625,3.8675,19,0,0,4

In [9]:
SBL = StatsBombLoader()
df_events = SBL.events(game_id=3788741)

df_actions = (
    spadl.add_names(df_actions)  # add actiontype and result names
    .merge(SBL.teams(game_id=3788741))  # add team names
    .merge(SBL.players(game_id=3788741))  # add player names
)
df_actions.head()

/Users/aranyeosakwe/oracle/.venv/lib/python3.12/site-packages/socceraction/data/statsbomb/loader.py:337: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  eventsdf["under_pressure"] = eventsdf["under_pressure"].fillna(False).astype(bool)
/Users/aranyeosakwe/oracle/.venv/lib/python3.12/site-packages/socceraction/data/statsbomb/loader.py:338: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  eventsdf["counterpress"] = eventsdf["counterpress"].fillna(False).astype(bool)
/Users/aranyeosakwe/oracle/.venv/lib/python3.12/site-packages/socceraction/data/statsbomb/loader.py:337: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  eventsdf["under_pressure"] = eventsdf["under_pressure"].fillna(False).astype(bool)
/Users/aranyeosakwe/oracle/.venv/lib/python3.12/site-packages/socceraction/data/statsbomb/loader.py:338: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  eventsdf["counterpress"] = eventsdf["counterpress"].fillna(False).astype(bool)

,game_id,original_event_id,period_id,time_seconds,team_id,player_id,start_x,start_y,end_x,end_y,...,result_name,bodypart_name,team_name,player_name,nickname,jersey_number,is_starter,starting_position_id,starting_position_name,minutes_played
0,3788741,5c888f58-fe77-459b-ab3b-a2fa5fb8ab16,1,0.878,909,11086.0,52.45625,34.0425,28.39375,43.5625,...,success,foot_right,Turkey,Burak Yılmaz,None,17,True,23,Center Forward,93
1,3788741,bea4235d-7e40-461c-bb82-6d473f5bb324,1,2.789,909,8963.0,28.39375,43.5625,31.63125,42.2025,...,success,foot,Turkey,Caglar Söyüncü,None,4,True,5,Left Center Back,93
2,3788741,84b9b798-0fbe-45bc-a4bf-3621959f29ce,1,4.288,909,8963.0,31.63125,42.2025,61.81875,3.6125,...,success,foot_left,Turkey,Caglar Söyüncü,None,4,True,5,Left Center Back,93
3,3788741,1615d483-101d-45c1-b554-04cf69897232,1,6.764,909,8541.0,61.81875,3.6125,61.55625,3.8675,...,success,foot,Turkey,Kenan Karaman,None,9,True,12,Right Midfield,75
4,3788741,39abab21-b9fc-4830-a7c4-f3cf6172df2c,1,6.866,909,8541.0,61.55625,3.8675,61.55625,3.8675,...,fail,foot,Turkey,Kenan Karaman,None,9,True,12,Right Midfield,75

In [10]:
import socceraction.atomic.spadl as atomicspadl

df_atomic = atomicspadl.convert_to_atomic(df_actions)
df_atomic.head(10)

,game_id,original_event_id,action_id,period_id,time_seconds,team_id,player_id,x,y,dx,dy,type_id,bodypart_id
0,3788741,5c888f58-fe77-459b-ab3b-a2fa5fb8ab16,0,1,0.8780,909,11086.0,52.45625,34.0425,-24.0625,9.520,0,5
1,3788741,5c888f58-fe77-459b-ab3b-a2fa5fb8ab16,1,1,1.8335,909,8963.0,28.39375,43.5625,0.0000,0.000,23,0
2,3788741,bea4235d-7e40-461c-bb82-6d473f5bb324,2,1,2.7890,909,8963.0,28.39375,43.5625,3.2375,-1.360,21,0
3,3788741,84b9b798-0fbe-45bc-a4bf-3621959f29ce,3,1,4.2880,909,8963.0,31.63125,42.2025,30.1875,-38.590,0,4
4,3788741,84b9b798-0fbe-45bc-a4bf-3621959f29ce,4,1,5.5260,909,8541.0,61.81875,3.6125,0.0000,0.000,23,0
5,3788741,1615d483-101d-45c1-b554-04cf69897232,5,1,6.7640,909,8541.0,61.81875,3.6125,-0.2625,0.255,21,0
6,3788741,39abab21-b9fc-4830-a7c4-f3cf6172df2c,6,1,6.8660,909,8541.0,61.55625,3.8675,0.0000,0.000,19,0
7,3788741,089acaca-894c-4b14-96a5-c845088af8ad,7,1,12.1630,914,8286.0,67.33125,0.0425,23.8875,6.290,2,2
8,3788741,089acaca-894c-4b14-96a5-c845088af8ad,8,1,13.1280,914,6954.0,91.21875,6.3325,0.0000,0.000,23,0
9,3788741,4cbd1088-1580-43f5-8b09-58efabb753ff,9,1,14.0930,914,6954.0,91.21875,6.3325,10.9375,4.420,21,0

In [11]:
import pandas as pd

df_competitions = api.competitions()

all_games = []
top_games = []
for row in df_competitions.itertuples(index=False):
   # print(row)
    df_games = api.games(competition_id=row.competition_id, season_id=row.season_id)
    all_games.append(df_games)

    if row.competition_name in top_leagues:
        df_top_games = api.games(
            competition_id=row.competition_id, season_id=row.season_id
        )
        top_games.append(df_top_games)

# Combine all results into a single DataFrame
df_all_games = pd.concat(all_games, ignore_index=True)
df_top_games = pd.concat(top_games, ignore_index=True)

In [12]:
df_all_games

,game_id,season_id,competition_id,competition_stage,game_day,game_date,home_team_id,away_team_id,home_score,away_score,venue,referee
0,3895292,281,9,Regular Season,28,2024-04-06 15:30:00,190,904,0,1,Stadion An der Alten Försterei,Benjamin Brand
1,3895320,281,9,Regular Season,31,2024-04-27 19:30:00,904,174,2,2,BayArena,Felix Zwayer
2,3895158,281,9,Regular Season,13,2023-12-03 18:30:00,904,180,1,1,BayArena,Daniel Siebert
3,3895107,281,9,Regular Season,7,2023-10-08 16:30:00,904,186,3,0,BayArena,Felix Zwayer
4,3895340,281,9,Regular Season,33,2024-05-12 20:30:00,868,904,0,5,Vonovia Ruhrstadion,Benjamin Brand
...,...,...,...,...,...,...,...,...,...,...,...,...
3956,22942,30,72,Group Stage,1,2019-06-11 13:00:00,1215,851,0,1,Stade Océane,NaN
3957,22984,30,72,Group Stage,3,2019-06-17 16:00:00,1216,857,0,4,Stade de la Mosson,Sandra Braz Bastos
3958,69199,30,72,Quarter-finals,5,2019-06-27 19:00:00,852,865,0,3,Stade Océane,Lucila Venegas Montes
3959,69205,30,72,Quarter-finals,5,2019-06-29 13:00:00,855,851,0,2,Stade du Hainaut,Claudia Umpiérrez
3960,69161,30,72,Round of 16,4,2019-06-24 16:00:00,863,1214,1,2,Stade Auguste-Delaune II,Katalin Kulcsar

In [13]:
df_top_games

,game_id,season_id,competition_id,competition_stage,game_day,game_date,home_team_id,away_team_id,home_score,away_score,venue,referee
0,3895292,281,9,Regular Season,28,2024-04-06 15:30:00,190,904,0,1,Stadion An der Alten Försterei,Benjamin Brand
1,3895320,281,9,Regular Season,31,2024-04-27 19:30:00,904,174,2,2,BayArena,Felix Zwayer
2,3895158,281,9,Regular Season,13,2023-12-03 18:30:00,904,180,1,1,BayArena,Daniel Siebert
3,3895107,281,9,Regular Season,7,2023-10-08 16:30:00,904,186,3,0,BayArena,Felix Zwayer
4,3895340,281,9,Regular Season,33,2024-05-12 20:30:00,868,904,0,5,Vonovia Ruhrstadion,Benjamin Brand
...,...,...,...,...,...,...,...,...,...,...,...,...
2521,3788743,43,55,Group Stage,1,2021-06-12 19:00:00,782,796,3,0,Saint-Petersburg Stadium ( Gazprom Arena ),Antonio Miguel Mateu Lahoz
2522,3788744,43,55,Group Stage,1,2021-06-12 13:00:00,907,773,1,1,Bakı Olimpiya Stadionu,Clément Turpin
2523,3887188,75,35,Final,12,1989-05-03 21:30:00,227,174,2,1,Stadio Diego Armando Maradona,Gerasimos Germanakos
2524,3750244,75,35,Semi-finals,10,1989-04-05 12:00:00,227,169,2,0,Stadio Diego Armando Maradona,Michel Vautrot
2525,3750245,75,35,Quarter-finals,9,1989-03-15 18:30:00,227,1076,3,0,Stadio Diego Armando Maradona,Siegfried Kirschen

# Events EDA

In [14]:
events.head()

,game_id,event_id,period_id,team_id,player_id,type_id,type_name,index,timestamp,minute,...,extra,related_events,player_name,position_id,position_name,location,under_pressure,counterpress,visible_area_360,freeze_frame_360
0,3788741,59645e89-9c7f-46f2-b662-332c5b8bba12,1,909,NaN,35,Starting XI,1,0 days 00:00:00,0,...,"{'tactics': {'formation': 4141, 'lineup': [{'p...",[],NaN,NaN,NaN,NaN,False,False,NaN,NaN
1,3788741,f063a4b6-f5ad-4576-b31d-a8dbe50f693e,1,914,NaN,35,Starting XI,2,0 days 00:00:00,0,...,"{'tactics': {'formation': 433, 'lineup': [{'pl...",[],NaN,NaN,NaN,NaN,False,False,NaN,NaN
2,3788741,4d9693c5-29bb-4e73-8913-7ee7a4e465fc,1,909,NaN,18,Half Start,3,0 days 00:00:00,0,...,{},[5c53ec59-b0d0-4515-8fee-d973e0037b56],NaN,NaN,NaN,NaN,False,False,NaN,NaN
3,3788741,5c53ec59-b0d0-4515-8fee-d973e0037b56,1,914,NaN,18,Half Start,4,0 days 00:00:00,0,...,{},[4d9693c5-29bb-4e73-8913-7ee7a4e465fc],NaN,NaN,NaN,NaN,False,False,NaN,NaN
4,3788741,5c888f58-fe77-459b-ab3b-a2fa5fb8ab16,1,909,11086.0,30,Pass,5,0 days 00:00:00.878000,0,...,"{'pass': {'recipient': {'id': 8963, 'name': 'C...",[776e11e0-9e85-4226-9f9e-edefa3685288],Burak Yılmaz,23.0,Center Forward,"[60.0, 40.0]",False,False,"[0.0, 27.7649873094419, 19.2332231959735, 17.3...","[{'teammate': False, 'actor': False, 'keeper':..."

In [15]:
events.columns

Index(['game_id', 'event_id', 'period_id', 'team_id', 'player_id', 'type_id',
       'type_name', 'index', 'timestamp', 'minute', 'second', 'possession',
       'possession_team_id', 'possession_team_name', 'play_pattern_id',
       'play_pattern_name', 'team_name', 'duration', 'extra', 'related_events',
       'player_name', 'position_id', 'position_name', 'location',
       'under_pressure', 'counterpress', 'visible_area_360',
       'freeze_frame_360'],
      dtype='object')

In [16]:
events["type_name"].unique()

array(['Starting XI', 'Half Start', 'Pass', 'Ball Receipt*', 'Carry',
       'Pressure', 'Miscontrol', 'Interception', 'Dribble', 'Duel',
       'Ball Recovery', 'Block', 'Shot', 'Goal Keeper', 'Clearance',
       'Dribbled Past', 'Foul Committed', 'Foul Won', 'Dispossessed',
       'Offside', 'Shield', 'Half End', 'Substitution', 'Tactical Shift',
       'Injury Stoppage', 'Own Goal Against', 'Own Goal For'],
      dtype=object)

In [17]:
events["play_pattern_name"]

0         Regular Play
1         Regular Play
2         Regular Play
3         Regular Play
4        From Kick Off
             ...
3798    From Goal Kick
3799    From Goal Kick
3800    From Goal Kick
3801    From Goal Kick
3802    From Goal Kick
Name: play_pattern_name, Length: 3803, dtype: object

In [18]:
df_atomic.head()

,game_id,original_event_id,action_id,period_id,time_seconds,team_id,player_id,x,y,dx,dy,type_id,bodypart_id
0,3788741,5c888f58-fe77-459b-ab3b-a2fa5fb8ab16,0,1,0.8780,909,11086.0,52.45625,34.0425,-24.0625,9.52,0,5
1,3788741,5c888f58-fe77-459b-ab3b-a2fa5fb8ab16,1,1,1.8335,909,8963.0,28.39375,43.5625,0.0000,0.00,23,0
2,3788741,bea4235d-7e40-461c-bb82-6d473f5bb324,2,1,2.7890,909,8963.0,28.39375,43.5625,3.2375,-1.36,21,0
3,3788741,84b9b798-0fbe-45bc-a4bf-3621959f29ce,3,1,4.2880,909,8963.0,31.63125,42.2025,30.1875,-38.59,0,4
4,3788741,84b9b798-0fbe-45bc-a4bf-3621959f29ce,4,1,5.5260,909,8541.0,61.81875,3.6125,0.0000,0.00,23,0

In [19]:
events = api.events(game_id=22912)
events.head()

/Users/aranyeosakwe/oracle/.venv/lib/python3.12/site-packages/socceraction/data/statsbomb/loader.py:337: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  eventsdf["under_pressure"] = eventsdf["under_pressure"].fillna(False).astype(bool)
/Users/aranyeosakwe/oracle/.venv/lib/python3.12/site-packages/socceraction/data/statsbomb/loader.py:338: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  eventsdf["counterpress"] = eventsdf["counterpress"].fillna(False).astype(bool)

,game_id,event_id,period_id,team_id,player_id,type_id,type_name,index,timestamp,minute,...,team_name,duration,extra,related_events,player_name,position_id,position_name,location,under_pressure,counterpress
0,22912,9ec3d009-c15b-4a8d-be80-57a07f40755a,1,38,NaN,35,Starting XI,1,0 days 00:00:00,0,...,Tottenham Hotspur,0.000000,"{'tactics': {'formation': 4231, 'lineup': [{'p...",[],NaN,NaN,NaN,NaN,False,False
1,22912,e8bdb5d1-8bcb-4a0d-bfd2-68c18c7f54d0,1,24,NaN,35,Starting XI,2,0 days 00:00:00,0,...,Liverpool,0.000000,"{'tactics': {'formation': 433, 'lineup': [{'pl...",[],NaN,NaN,NaN,NaN,False,False
2,22912,00b678a4-3767-4d0b-92e6-9cb4c959d94d,1,24,NaN,18,Half Start,3,0 days 00:00:00,0,...,Liverpool,0.000000,{},[05840f64-0fb7-4f2d-885a-49790d6bd4df],NaN,NaN,NaN,NaN,False,False
3,22912,05840f64-0fb7-4f2d-885a-49790d6bd4df,1,38,NaN,18,Half Start,4,0 days 00:00:00,0,...,Tottenham Hotspur,0.000000,{},[00b678a4-3767-4d0b-92e6-9cb4c959d94d],NaN,NaN,NaN,NaN,False,False
4,22912,b67ef6a9-e877-4dbe-bb03-edcc9d8c7711,1,24,3532.0,30,Pass,5,0 days 00:00:00.208000,0,...,Liverpool,1.666205,"{'pass': {'recipient': {'id': 3502, 'name': 'J...",[c7297515-ae92-4fb4-93a8-59745b8dfa90],Jordan Brian Henderson,13.0,Right Center Midfield,"[61.0, 40.1]",False,False

In [20]:
events.isnull().sum()

game_id                   0
event_id                  0
period_id                 0
team_id                   0
player_id                16
type_id                   0
type_name                 0
index                     0
timestamp                 0
minute                    0
second                    0
possession                0
possession_team_id        0
possession_team_name      0
play_pattern_id           0
play_pattern_name         0
team_name                 0
duration                846
extra                     0
related_events            0
player_name              16
position_id              16
position_name            16
location                 25
under_pressure            0
counterpress              0
dtype: int64

In [21]:
events[events["type_name"] == "Shot"]["extra"]#["extra"][33]['shot']['outcome']

33      {'shot': {'statsbomb_xg': 0.7835, 'end_locatio...
341     {'shot': {'statsbomb_xg': 0.026188651, 'end_lo...
586     {'shot': {'statsbomb_xg': 0.0062032556, 'end_l...
757     {'shot': {'statsbomb_xg': 0.03979926, 'end_loc...
767     {'shot': {'statsbomb_xg': 0.007077651, 'end_lo...
1346    {'shot': {'statsbomb_xg': 0.0091631785, 'end_l...
1352    {'shot': {'statsbomb_xg': 0.038274758, 'end_lo...
1401    {'shot': {'statsbomb_xg': 0.018781843, 'end_lo...
1422    {'shot': {'statsbomb_xg': 0.021911133, 'end_lo...
1560    {'shot': {'statsbomb_xg': 0.045138687, 'end_lo...
1884    {'shot': {'statsbomb_xg': 0.020487793, 'end_lo...
1915    {'shot': {'statsbomb_xg': 0.046969783, 'end_lo...
1959    {'shot': {'statsbomb_xg': 0.11269027, 'end_loc...
2032    {'shot': {'statsbomb_xg': 0.020857124, 'end_lo...
2038    {'shot': {'statsbomb_xg': 0.057148643, 'end_lo...
2177    {'shot': {'statsbomb_xg': 0.022679387, 'end_lo...
2434    {'shot': {'statsbomb_xg': 0.044091757, 'end_lo...
2581    {'shot': {'statsbomb_xg': 0.06948169, 'end_loc...
2793    {'shot': {'statsbomb_xg': 0.1563633, 'end_loca...
2843    {'shot': {'statsbomb_xg': 0.027245786, 'end_lo...
2850    {'shot': {'statsbomb_xg': 0.07394664, 'end_loc...
2886    {'shot': {'statsbomb_xg': 0.040406317, 'end_lo...
2912    {'shot': {'statsbomb_xg': 0.026962453, 'end_lo...
2942    {'shot': {'statsbomb_xg': 0.008574429, 'end_lo...
2947    {'shot': {'statsbomb_xg': 0.12961794, 'end_loc...
2970    {'shot': {'statsbomb_xg': 0.061952036, 'end_lo...
2979    {'shot': {'statsbomb_xg': 0.077972755, 'end_lo...
3075    {'shot': {'statsbomb_xg': 0.026976045, 'end_lo...
3091    {'shot': {'statsbomb_xg': 0.05625648, 'end_loc...
3103    {'shot': {'statsbomb_xg': 0.05069226, 'end_loc...
Name: extra, dtype: object

In [22]:
df_actions = spadl.statsbomb.convert_to_actions(events, home_team_id=38)
df_actions = (
    spadl.add_names(df_actions)  # add actiontype and result names
    .merge(SBL.teams(game_id=22912))  # add team names
    .merge(SBL.players(game_id=22912))  # add player names
)
df_atomic = atomicspadl.convert_to_atomic(df_actions)
df_atomic

/Users/aranyeosakwe/oracle/.venv/lib/python3.12/site-packages/socceraction/spadl/statsbomb.py:53: UserWarning: Inferred xy_fidelity_version=2. If this is incorrect, please specify the correct version using the xy_fidelity_version argument
  warnings.warn(
/Users/aranyeosakwe/oracle/.venv/lib/python3.12/site-packages/socceraction/spadl/statsbomb.py:75: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  events["extra"].fillna({}, inplace=True)
/Users/aranyeosakwe/oracle/.venv/lib/python3.12/site-packages/socceraction/data/statsbomb/loader.py:337: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  eventsdf["under_pressure"] = eventsdf["under_pressure"].fillna(False).astype(bool)
/Users/aranyeosakwe/oracle/.venv/lib/python3.12/site-packages/socceraction/data/statsbomb/loader.py:338: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  eventsdf["counterpress"] = eventsdf["counterpress"].fillna(False).astype(bool)

,game_id,original_event_id,action_id,period_id,time_seconds,team_id,player_id,x,y,dx,dy,type_id,bodypart_id
0,22912,b67ef6a9-e877-4dbe-bb03-edcc9d8c7711,0,1,0.2080,24,3532.0,51.66875,34.0425,23.6250,3.145,0,5
1,22912,b67ef6a9-e877-4dbe-bb03-edcc9d8c7711,1,1,1.0415,24,3502.0,75.29375,37.1875,0.0000,0.000,23,0
2,22912,609587a5-193c-469b-be3c-63131c646e59,2,1,1.8750,24,3502.0,75.29375,37.1875,-1.8375,0.170,21,0
3,22912,10f8eed9-fa49-4170-9057-d9418e9546ae,3,1,3.3580,24,3502.0,73.45625,37.3575,-44.1875,-34.425,0,5
4,22912,10f8eed9-fa49-4170-9057-d9418e9546ae,4,1,4.3780,38,3308.0,29.26875,2.9325,0.0000,0.000,10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2714,22912,f63b45b8-83d8-403c-b950-eb995803b89a,2714,2,2985.7785,24,3664.0,55.69375,50.3625,0.0000,0.000,23,0
2715,22912,f45ba1ef-aab6-43ab-98d5-19edaf8e3190,2715,2,2986.7030,24,3664.0,55.69375,50.3625,0.0000,0.000,21,0
2716,22912,7d6d31bc-c05d-4b24-bdd6-0e65b186c864,2716,2,2987.0130,24,3664.0,55.69375,50.3625,-35.4375,17.425,0,5
2717,22912,7d6d31bc-c05d-4b24-bdd6-0e65b186c864,2717,2,2990.6925,24,3664.0,20.25625,67.7875,0.0000,0.000,25,0
2718,22912,3b5e7262-9bfc-4283-af7e-a5248489cc6b,2718,2,2994.3720,38,3077.0,19.20625,67.9575,-12.0750,-17.510,2,2

In [23]:
df_actions.head()

,game_id,original_event_id,period_id,time_seconds,team_id,player_id,start_x,start_y,end_x,end_y,...,result_name,bodypart_name,team_name,player_name,nickname,jersey_number,is_starter,starting_position_id,starting_position_name,minutes_played
0,22912,b67ef6a9-e877-4dbe-bb03-edcc9d8c7711,1,0.208,24,3532.0,51.66875,34.0425,75.29375,37.1875,...,success,foot_right,Liverpool,Jordan Brian Henderson,Jordan Henderson,14,True,13,Right Center Midfield,97
1,22912,609587a5-193c-469b-be3c-63131c646e59,1,1.875,24,3502.0,75.29375,37.1875,73.45625,37.3575,...,success,foot,Liverpool,Joël Andre Job Matip,Joël Matip,32,True,3,Right Center Back,97
2,22912,10f8eed9-fa49-4170-9057-d9418e9546ae,1,3.358,24,3502.0,73.45625,37.3575,29.26875,2.9325,...,fail,foot_right,Liverpool,Joël Andre Job Matip,Joël Matip,32,True,3,Right Center Back,97
3,22912,3cb70cbe-9267-43eb-8937-b1f8d00cc902,1,5.398,38,3308.0,29.26875,2.9325,47.64375,12.0275,...,fail,head,Tottenham Hotspur,Kieran Trippier,None,2,True,2,Right Back,97
4,22912,9babcee7-0db0-4cf5-bbd3-b6ca2c0ff6e2,1,7.704,24,3247.0,47.64375,12.0275,32.59375,14.4925,...,fail,head,Liverpool,Fábio Henrique Tavares,Fabinho,3,True,10,Center Defensive Midfield,97

In [24]:
df_actions['type_name'].unique()

array(['pass', 'dribble', 'foul', 'shot_penalty', 'clearance', 'throw_in',
       'interception', 'bad_touch', 'tackle', 'corner_crossed', 'take_on',
       'shot', 'goalkick', 'keeper_punch', 'freekick_short', 'cross',
       'keeper_claim', 'corner_short', 'keeper_save', 'freekick_crossed',
       'shot_freekick'], dtype=object)

## Question: Given an event id, build ML dataset with
Home/Away goals scored at time of event
Home/Away yellows at time of event
Home/away red cards at time of event
Previous event sequence 
Event contains home team indicator, event type, x/y coordinates, time since previous event, accurate

In [25]:
events.head()

,game_id,event_id,period_id,team_id,player_id,type_id,type_name,index,timestamp,minute,...,team_name,duration,extra,related_events,player_name,position_id,position_name,location,under_pressure,counterpress
0,22912,9ec3d009-c15b-4a8d-be80-57a07f40755a,1,38,NaN,35,Starting XI,1,0 days 00:00:00,0,...,Tottenham Hotspur,0.000000,"{'tactics': {'formation': 4231, 'lineup': [{'p...",[],NaN,NaN,NaN,NaN,False,False
1,22912,e8bdb5d1-8bcb-4a0d-bfd2-68c18c7f54d0,1,24,NaN,35,Starting XI,2,0 days 00:00:00,0,...,Liverpool,0.000000,"{'tactics': {'formation': 433, 'lineup': [{'pl...",[],NaN,NaN,NaN,NaN,False,False
2,22912,00b678a4-3767-4d0b-92e6-9cb4c959d94d,1,24,NaN,18,Half Start,3,0 days 00:00:00,0,...,Liverpool,0.000000,{},[05840f64-0fb7-4f2d-885a-49790d6bd4df],NaN,NaN,NaN,NaN,False,False
3,22912,05840f64-0fb7-4f2d-885a-49790d6bd4df,1,38,NaN,18,Half Start,4,0 days 00:00:00,0,...,Tottenham Hotspur,0.000000,{},[00b678a4-3767-4d0b-92e6-9cb4c959d94d],NaN,NaN,NaN,NaN,False,False
4,22912,b67ef6a9-e877-4dbe-bb03-edcc9d8c7711,1,24,3532.0,30,Pass,5,0 days 00:00:00.208000,0,...,Liverpool,1.666205,"{'pass': {'recipient': {'id': 3502, 'name': 'J...",[c7297515-ae92-4fb4-93a8-59745b8dfa90],Jordan Brian Henderson,13.0,Right Center Midfield,"[61.0, 40.1]",False,False

In [26]:
df_actions.head()

,game_id,original_event_id,period_id,time_seconds,team_id,player_id,start_x,start_y,end_x,end_y,...,result_name,bodypart_name,team_name,player_name,nickname,jersey_number,is_starter,starting_position_id,starting_position_name,minutes_played
0,22912,b67ef6a9-e877-4dbe-bb03-edcc9d8c7711,1,0.208,24,3532.0,51.66875,34.0425,75.29375,37.1875,...,success,foot_right,Liverpool,Jordan Brian Henderson,Jordan Henderson,14,True,13,Right Center Midfield,97
1,22912,609587a5-193c-469b-be3c-63131c646e59,1,1.875,24,3502.0,75.29375,37.1875,73.45625,37.3575,...,success,foot,Liverpool,Joël Andre Job Matip,Joël Matip,32,True,3,Right Center Back,97
2,22912,10f8eed9-fa49-4170-9057-d9418e9546ae,1,3.358,24,3502.0,73.45625,37.3575,29.26875,2.9325,...,fail,foot_right,Liverpool,Joël Andre Job Matip,Joël Matip,32,True,3,Right Center Back,97
3,22912,3cb70cbe-9267-43eb-8937-b1f8d00cc902,1,5.398,38,3308.0,29.26875,2.9325,47.64375,12.0275,...,fail,head,Tottenham Hotspur,Kieran Trippier,None,2,True,2,Right Back,97
4,22912,9babcee7-0db0-4cf5-bbd3-b6ca2c0ff6e2,1,7.704,24,3247.0,47.64375,12.0275,32.59375,14.4925,...,fail,head,Liverpool,Fábio Henrique Tavares,Fabinho,3,True,10,Center Defensive Midfield,97

In [27]:
df_actions.columns

Index(['game_id', 'original_event_id', 'period_id', 'time_seconds', 'team_id',
       'player_id', 'start_x', 'start_y', 'end_x', 'end_y', 'type_id',
       'result_id', 'bodypart_id', 'action_id', 'type_name', 'result_name',
       'bodypart_name', 'team_name', 'player_name', 'nickname',
       'jersey_number', 'is_starter', 'starting_position_id',
       'starting_position_name', 'minutes_played'],
      dtype='object')

In [28]:
df_atomic.head()

,game_id,original_event_id,action_id,period_id,time_seconds,team_id,player_id,x,y,dx,dy,type_id,bodypart_id
0,22912,b67ef6a9-e877-4dbe-bb03-edcc9d8c7711,0,1,0.2080,24,3532.0,51.66875,34.0425,23.6250,3.145,0,5
1,22912,b67ef6a9-e877-4dbe-bb03-edcc9d8c7711,1,1,1.0415,24,3502.0,75.29375,37.1875,0.0000,0.000,23,0
2,22912,609587a5-193c-469b-be3c-63131c646e59,2,1,1.8750,24,3502.0,75.29375,37.1875,-1.8375,0.170,21,0
3,22912,10f8eed9-fa49-4170-9057-d9418e9546ae,3,1,3.3580,24,3502.0,73.45625,37.3575,-44.1875,-34.425,0,5
4,22912,10f8eed9-fa49-4170-9057-d9418e9546ae,4,1,4.3780,38,3308.0,29.26875,2.9325,0.0000,0.000,10,0

In [29]:
df_atomic[[]]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[2719 rows x 0 columns]

In [30]:
df_atomic.groupby("type_id")["action_id"].count()

type_id
0     764
1      18
2      54
7      15
8      15
9      24
10    202
11     28
12      1
14      9
15      5
16      3
18     51
19     22
21    719
22     19
23    671
25     61
26      4
27      2
31     17
32     15
Name: action_id, dtype: int64

In [34]:
atomicspadl.add_names(df_atomic)['type_name'].unique()

array(['pass', 'receival', 'dribble', 'interception', 'foul',
       'shot_penalty', 'goal', 'clearance', 'out', 'throw_in',
       'bad_touch', 'tackle', 'corner', 'take_on', 'shot', 'goalkick',
       'keeper_punch', 'freekick', 'cross', 'keeper_claim', 'offside',
       'keeper_save'], dtype=object)

In [36]:
df_actions.columns

Index(['game_id', 'original_event_id', 'period_id', 'time_seconds', 'team_id',
       'player_id', 'start_x', 'start_y', 'end_x', 'end_y', 'type_id',
       'result_id', 'bodypart_id', 'action_id', 'type_name', 'result_name',
       'bodypart_name', 'team_name', 'player_name', 'nickname',
       'jersey_number', 'is_starter', 'starting_position_id',
       'starting_position_name', 'minutes_played'],
      dtype='object')

In [39]:
df_actions['prev_action_time'] = df_actions['time_seconds'].shift(1, fill_value=0)

In [41]:
df_actions["time_elapsed"] = df_actions["time_seconds"] - df_actions["prev_action_time"]

In [44]:
df_actions['time_elapsed'].max()

101.26099999999997

In [50]:
df_actions[df_actions['time_elapsed'] == df_actions['time_elapsed'].max()]

,game_id,original_event_id,period_id,time_seconds,team_id,player_id,start_x,start_y,end_x,end_y,...,team_name,player_name,nickname,jersey_number,is_starter,starting_position_id,starting_position_name,minutes_played,prev_action_time,time_elapsed
774,22912,4b20f726-252a-445a-9386-0b4d0a30cf83,1,2413.727,38,3099.0,5.20625,37.4425,65.66875,38.6325,...,Tottenham Hotspur,Hugo Lloris,None,1,True,1,Goalkeeper,97,2312.466,101.261

In [53]:
pd.set_option("display.max_columns", None)

df_actions[df_actions["time_elapsed"] == df_actions["time_elapsed"].min()]

,game_id,original_event_id,period_id,time_seconds,team_id,player_id,start_x,start_y,end_x,end_y,type_id,result_id,bodypart_id,action_id,type_name,result_name,bodypart_name,team_name,player_name,nickname,jersey_number,is_starter,starting_position_id,starting_position_name,minutes_played,prev_action_time,time_elapsed
931,22912,9659946c-1e8d-44fb-a8a8-a2dae399e440,2,0.426,38,3082.0,53.33125,33.9575,32.50625,29.2825,0,1,5,931,pass,success,foot_right,Tottenham Hotspur,Harry Winks,None,8,True,15,Left Center Midfield,67,2810.757,-2810.331

In [56]:
ml_cols = ['original_event_id', 'time_seconds', 'start_x', 'start_y', 'type_name', 'result_name']
df_actions[ml_cols]

,original_event_id,time_seconds,start_x,start_y,type_name,result_name
0,b67ef6a9-e877-4dbe-bb03-edcc9d8c7711,0.208,51.66875,34.0425,pass,success
1,609587a5-193c-469b-be3c-63131c646e59,1.875,75.29375,37.1875,dribble,success
2,10f8eed9-fa49-4170-9057-d9418e9546ae,3.358,73.45625,37.3575,pass,fail
3,3cb70cbe-9267-43eb-8937-b1f8d00cc902,5.398,29.26875,2.9325,pass,fail
4,9babcee7-0db0-4cf5-bbd3-b6ca2c0ff6e2,7.704,47.64375,12.0275,pass,fail
...,...,...,...,...,...,...
1788,1bcd7e87-ea20-44f9-bf3c-82e30f113b57,2982.848,19.38125,22.0575,pass,fail
1789,f63b45b8-83d8-403c-b950-eb995803b89a,2984.854,70.30625,44.0725,pass,success
1790,f45ba1ef-aab6-43ab-98d5-19edaf8e3190,2986.703,55.69375,50.3625,dribble,success
1791,7d6d31bc-c05d-4b24-bdd6-0e65b186c864,2987.013,55.69375,50.3625,pass,fail
1792,3b5e7262-9bfc-4283-af7e-a5248489cc6b,2994.372,19.20625,67.9575,throw_in,success